# version: '3.8' # Versi ini opsional dan bisa dihapus

networks:
    # Mendefinisikan bahwa kita akan menggunakan jaringan yang sudah ada di luar sana
    iae_shared_network:
        external: true

services:
    # ====================================================================
    # PROXY PUSAT (API GATEWAY) - Dijalankan dari file ini
    # ====================================================================
    api_gateway:
        image: jwilder/nginx-proxy
        container_name: api_gateway_proxy # Nama generik untuk proxy utama
        ports:
            # Gunakan port 80 agar semua layanan bisa diakses tanpa mengetik port
            - "80:80"
            - "443:443"
        volumes:
            - /var/run/docker.sock:/tmp/docker.sock:ro
        restart: always
        networks:
            # Terhubung ke jaringan bersama
            - iae_shared_network

    # ====================================================================
    # LAYANAN SPESIFIK UNTUK BUKU
    # ====================================================================

    # Web server (Nginx/Apache) yang melayani request untuk aplikasi PHP
    buku_web:
        build:
            context: ./
            dockerfile: docker/dev/web.docker
        container_name: buku_web_server
        volumes:
            - ./:/var/www
        depends_on:
            - buku_app
        environment:
            # Proxy akan mendeteksi VIRTUAL_HOST ini
            - VIRTUAL_HOST=api.buku.test
        expose:
            - "80" # WAJIB agar ditemukan oleh proxy
        networks:
            # Terhubung ke jaringan bersama
            - iae_shared_network

    # Aplikasi (PHP-FPM)
    buku_app:
        build:
            context: ./
            dockerfile: docker/dev/app.docker
        container_name: buku_app
        volumes:
            - ./:/var/www
        depends_on:
            - buku_db
            - buku_cache
        environment:
            - DB_CONNECTION=mysql
            - DB_HOST=buku_db
            - DB_PORT=3306
            - DB_DATABASE=buku_service
            - DB_USERNAME=root
            - DB_PASSWORD=123
            - REDIS_HOST=buku_cache
            - REDIS_PORT=6379
        networks:
            # Terhubung ke jaringan bersama
            - iae_shared_network

    # Database
    buku_db:
        image: mysql:8.2
        container_name: buku_db
        environment:
            - MYSQL_ROOT_PASSWORD=123
            - MYSQL_DATABASE=buku_service
        ports:
            - "33067:3306" # Port unik untuk layanan ini
        volumes:
            - buku_data:/var/lib/mysql
        networks:
            # Terhubung ke jaringan bersama
            - iae_shared_network

    # Cache
    buku_cache:
        image: redis:latest
        container_name: buku_cache
        ports:
            - "63797:6379" # Port unik untuk layanan ini
        networks:
            # Terhubung ke jaringan bersama
            - iae_shared_network

    # PhpMyAdmin untuk mengelola database
    buku_phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: buku_phpmyadmin
        depends_on:
            - buku_db
        environment:
            - PMA_HOST=buku_db
            - PMA_USER=root
            - PMA_PASSWORD=123
            - VIRTUAL_HOST=pma.buku.test
        expose:
            - "80" # WAJIB agar ditemukan oleh proxy
        networks:
            # Terhubung ke jaringan bersama
            - iae_shared_network

volumes:
    buku_data:
