# version: '4'

networks:
    iae_shared_network:
        external: true

services:
    # TIDAK ADA PROXY DI SINI
    # Layanan ini akan dideteksi secara otomatis oleh api_gateway_proxy

    # Web server (Nginx/Apache) yang melayani request untuk aplikasi PHP
    buku_web:
        build:
            context: ./
            dockerfile: docker/dev/web.docker
        container_name: buku_web_server
        volumes:
            - ./:/var/www
        depends_on:
            - buku_app
        environment:
            - VIRTUAL_HOST=api.buku.test
        expose:
            - "80" # WAJIB agar ditemukan oleh proxy utama
        networks:
            - iae_shared_network

    # Aplikasi (PHP-FPM)
    buku_app:
        build:
            context: ./
            dockerfile: docker/dev/app.docker
        container_name: buku_app
        volumes:
            - ./:/var/www
        depends_on:
            - buku_db
            - buku_cache
        environment:
            - DB_CONNECTION=mysql
            - DB_HOST=buku_db
            - DB_PORT=3306
            - DB_DATABASE=buku_service
            - DB_USERNAME=root
            - DB_PASSWORD=123
            - REDIS_HOST=buku_cache
            - REDIS_PORT=6379
        networks:
            - iae_shared_network

    # Database
    buku_db:
        image: mysql:8.2
        container_name: buku_db
        environment:
            - MYSQL_ROOT_PASSWORD=123
            - MYSQL_DATABASE=buku_service
        ports:
            - "33067:3306" # Port unik untuk layanan ini
        volumes:
            - buku_data:/var/lib/mysql
        networks:
            - iae_shared_network

    # Cache
    buku_cache:
        image: redis:latest
        container_name: buku_cache
        ports:
            - "63797:6379" # Port unik untuk layanan ini
        networks:
            - iae_shared_network

    # PhpMyAdmin untuk mengelola database
    buku_phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: buku_phpmyadmin
        depends_on:
            - buku_db
        environment:
            - PMA_HOST=buku_db
            - PMA_USER=root
            - PMA_PASSWORD=123
            - VIRTUAL_HOST=pma.buku.test
        expose:
            - "80" # WAJIB agar ditemukan oleh proxy utama
        networks:
            - iae_shared_network

volumes:
    buku_data: