# version: '4'

networks:
    iae_shared_network:
        external: true

services:
    # Proxy tidak diperlukan di sini. Gunakan satu proxy utama yang sudah berjalan
    # di docker-compose lain untuk menangani semua VIRTUAL_HOST.

    # Web server (Nginx/Apache) untuk layanan Peminjaman
    peminjaman_web:
        build:
            context: ./
            dockerfile: docker/dev/web.docker
        container_name: peminjaman_web_server
        volumes:
            - ./:/var/www
        depends_on:
            - peminjaman_app
        environment:
            - VIRTUAL_HOST=api.peminjaman.test
        expose:
            - "80" # WAJIB agar ditemukan oleh proxy utama
        networks:
            - iae_shared_network

    # Aplikasi (PHP-FPM) untuk layanan Peminjaman
    peminjaman_app:
        build:
            context: ./
            dockerfile: docker/dev/app.docker
        container_name: peminjaman_app
        volumes:
            - ./:/var/www
        depends_on:
            - peminjaman_db
            - peminjaman_cache
        environment:
            # Koneksi ke Redis
            - REDIS_PORT=6379
            - REDIS_HOST=peminjaman_cache
            # Koneksi ke Database Peminjaman
            - DB_CONNECTION=mysql
            - DB_HOST=peminjaman_db
            - DB_PORT=3306
            - DB_DATABASE=peminjaman_service
            - DB_USERNAME=root
            - DB_PASSWORD=123
        networks:
            - iae_shared_network

    # Database untuk layanan Peminjaman
    peminjaman_db:
        image: mysql:8.2
        container_name: peminjaman_db
        environment:
            - MYSQL_ROOT_PASSWORD=123
            - MYSQL_DATABASE=peminjaman_service
        ports:
            # Port diubah menjadi berikutnya agar tidak konflik
            - "33070:3306" 
        volumes:
            - peminjaman_data:/var/lib/mysql
        networks:
            - iae_shared_network

    # Cache untuk layanan Peminjaman
    peminjaman_cache:
        image: redis:latest
        container_name: peminjaman_cache
        ports:
            # Port diubah menjadi berikutnya agar tidak konflik
            - "63800:6379"
        networks:
            - iae_shared_network

    # PhpMyAdmin untuk mengelola database Peminjaman
    peminjaman_phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: peminjaman_phpmyadmin
        depends_on:
            - peminjaman_db
        environment:
            - PMA_HOST=peminjaman_db
            - PMA_USER=root
            - PMA_PASSWORD=123
            - VIRTUAL_HOST=pma.peminjaman.test
        expose:
            - "80" # WAJIB agar ditemukan oleh proxy utama
        networks:
            - iae_shared_network

volumes:
    peminjaman_data: