# version: '4'

networks:
    iae_shared_network:
        external: true

services:
    # ====================================================================
    # PROXY PUSAT (API GATEWAY) - HANYA ADA DI FILE INI
    # ====================================================================
    api_gateway:
        image: jwilder/nginx-proxy
        container_name: api_gateway_proxy # Nama generik untuk proxy utama
        ports:
            - "80:80"   # Port utama untuk semua traffic HTTP
            - "443:443" # Port utama untuk semua traffic HTTPS
        volumes:
            - /var/run/docker.sock:/tmp/docker.sock:ro
        restart: always
        networks:
            - iae_shared_network

    # ====================================================================
    # LAYANAN SPESIFIK UNTUK ENROLLMENT
    # ====================================================================

    # Web server (Nginx/Apache) untuk layanan Enrollment
    enrollment_web:
        build:
            context: ./
            dockerfile: docker/dev/web.docker
        container_name: enrollment_web_server
        volumes:
            - ./:/var/www
        depends_on:
            - enrollment_app
        environment:
            - VIRTUAL_HOST=api.enrollment.test
        expose:
            - "80" # WAJIB agar ditemukan oleh proxy utama
        networks:
            - iae_shared_network

    # Aplikasi (PHP-FPM) untuk layanan Enrollment
    enrollment_app:
        build:
            context: ./
            dockerfile: docker/dev/app.docker
        container_name: enrollment_app
        volumes:
            - ./:/var/www
        depends_on:
            - enrollment_db
            - enrollment_cache
        environment:
            # Variabel koneksi lengkap untuk Laravel
            - DB_CONNECTION=mysql
            - DB_HOST=enrollment_db
            - DB_PORT=3306
            - DB_DATABASE=db_enroll
            - DB_USERNAME=root
            - DB_PASSWORD=123
            - REDIS_HOST=enrollment_cache
            - REDIS_PORT=6379
        networks:
            - iae_shared_network

    # Database untuk layanan Enrollment
    enrollment_db:
        image: mysql:8.2
        container_name: enrollment_db
        environment:
            - MYSQL_ROOT_PASSWORD=123
            - MYSQL_DATABASE=db_enroll
        ports:
            - "33072:3306" # Port unik untuk layanan ini
        volumes:
            - enrollment_data:/var/lib/mysql
        networks:
            - iae_shared_network

    # Cache untuk layanan Enrollment
    enrollment_cache:
        image: redis:latest
        container_name: enrollment_cache
        ports:
            - "63802:6379" # Port unik untuk layanan ini
        networks:
            - iae_shared_network

    # PhpMyAdmin untuk mengelola database Enrollment
    enrollment_phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: enrollment_phpmyadmin
        depends_on:
            - enrollment_db
        environment:
            - PMA_HOST=enrollment_db
            - PMA_USER=root
            - PMA_PASSWORD=123
            - VIRTUAL_HOST=pma.enrollment.test
        expose:
            - "80" # WAJIB agar ditemukan oleh proxy utama
        networks:
            - iae_shared_network

volumes:
    enrollment_data: