# version: '4'

networks:
    iae_shared_network:
        external: true

services:
    # Proxy tidak diperlukan di sini. Gunakan satu proxy utama yang sudah berjalan
    # di docker-compose lain untuk menangani semua VIRTUAL_HOST.

    # Web server (Nginx/Apache) untuk layanan User
    user_web:
        build:
            context: ./
            dockerfile: docker/dev/web.docker
        container_name: user_web_server # Nama lebih deskriptif
        volumes:
            - ./:/var/www
        depends_on:
            - user_app
        environment:
            - VIRTUAL_HOST=api.user.test
        expose:
            - "80" # WAJIB agar ditemukan oleh proxy utama
        networks:
            - iae_shared_network

    # Aplikasi (PHP-FPM) untuk layanan User
    user_app:
        build:
            context: ./
            dockerfile: docker/dev/app.docker
        container_name: user_app
        volumes:
            - ./:/var/www
        depends_on:
            - user_db
            - user_cache
        environment:
            # Koneksi ke Redis
            - REDIS_PORT=6379
            - REDIS_HOST=user_cache
            # Koneksi ke Database User
            - DB_CONNECTION=mysql
            - DB_HOST=user_db
            - DB_PORT=3306
            - DB_DATABASE=user_service
            - DB_USERNAME=root
            - DB_PASSWORD=123
        networks:
            - iae_shared_network

    # Database untuk layanan User
    user_db:
        image: mysql:8.2
        container_name: user_db
        environment:
            - MYSQL_ROOT_PASSWORD=123
            - MYSQL_DATABASE=user_service
        ports:
            # Port diubah menjadi berikutnya agar tidak konflik
            - "33069:3306" 
        volumes:
            - user_data:/var/lib/mysql
        networks:
            - iae_shared_network

    # Cache untuk layanan User
    user_cache:
        image: redis:latest
        container_name: user_cache
        ports:
            # Port diubah menjadi berikutnya agar tidak konflik
            - "63799:6379"
        networks:
            - iae_shared_network

    # PhpMyAdmin untuk mengelola database User
    user_phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: user_phpmyadmin
        depends_on:
            - user_db
        environment:
            - PMA_HOST=user_db
            - PMA_USER=root
            - PMA_PASSWORD=123
            - VIRTUAL_HOST=pma.user.test
        expose:
            - "80" # WAJIB agar ditemukan oleh proxy utama
        networks:
            - iae_shared_network

volumes:
    user_data:

