# version: '4'

networks:
    iae_shared_network:
        external: true

services:
    # Proxy tidak diperlukan di sini. Gunakan satu proxy utama yang sudah berjalan
    # di docker-compose lain untuk menangani semua VIRTUAL_HOST.

    # Web server (Nginx/Apache) untuk layanan Pengembalian
    pengembalian_web:
        build:
            context: ./
            dockerfile: docker/dev/web.docker
        container_name: pengembalian_web_server # Nama lebih deskriptif
        volumes:
            - ./:/var/www
        depends_on:
            - pengembalian_app
        environment:
            - VIRTUAL_HOST=api.pengembalian.test
        expose:
            - "80" # WAJIB agar ditemukan oleh proxy utama
        networks:
            - iae_shared_network

    # Aplikasi (PHP-FPM) untuk layanan Pengembalian
    pengembalian_app:
        build:
            context: ./
            dockerfile: docker/dev/app.docker
        container_name: pengembalian_app
        volumes:
            - ./:/var/www
        depends_on:
            - pengembalian_db
            - pengembalian_cache
        environment:
            # Koneksi ke Redis
            - REDIS_PORT=6379
            - REDIS_HOST=pengembalian_cache
            # Koneksi ke Database Pengembalian
            - DB_CONNECTION=mysql
            - DB_HOST=pengembalian_db
            - DB_PORT=3306
            - DB_DATABASE=pengembalian_service
            - DB_USERNAME=root
            - DB_PASSWORD=123
        networks:
            - iae_shared_network

    # Database untuk layanan Pengembalian
    pengembalian_db:
        image: mysql:8.2
        container_name: pengembalian_db
        environment:
            - MYSQL_ROOT_PASSWORD=123
            - MYSQL_DATABASE=pengembalian_service
        ports:
            # Port diubah menjadi berikutnya agar tidak konflik
            - "33071:3306" 
        volumes:
            - pengembalian_data:/var/lib/mysql
        networks:
            - iae_shared_network

    # Cache untuk layanan Pengembalian
    pengembalian_cache:
        image: redis:latest
        container_name: pengembalian_cache
        ports:
            # Port diubah menjadi berikutnya agar tidak konflik
            - "63801:6379"
        networks:
            - iae_shared_network

    # PhpMyAdmin untuk mengelola database Pengembalian
    pengembalian_phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: pengembalian_phpmyadmin
        depends_on:
            - pengembalian_db
        environment:
            - PMA_HOST=pengembalian_db
            - PMA_USER=root
            - PMA_PASSWORD=123
            - VIRTUAL_HOST=pma.pengembalian.test
        expose:
            - "80" # WAJIB agar ditemukan oleh proxy utama
        networks:
            - iae_shared_network

volumes:
    pengembalian_data: