# version: '3'

networks:
    iae_shared_network:
        external: true

services:
    denda_nginx_proxy:
        image: jwilder/nginx-proxy
        container_name: denda_nginx_proxy
        ports:
            - "8080:80"
        volumes:
            - /var/run/docker.sock:/tmp/docker.sock:ro
        networks:
            - iae_shared_network

    denda_web:
        build:
            context: ./
            dockerfile: docker/dev/web.docker
        container_name: denda_nginx
        # ports:
        #     - "8080:80"
        volumes:
            - ./:/var/www
        depends_on:
            - denda_app
        environment:
            - VIRTUAL_HOST=api.denda.test
        networks:
            - iae_shared_network

    denda_app:
        build:
            context: ./
            dockerfile: docker/dev/app.docker
        container_name: denda_app
        volumes:
            - ./:/var/www
        depends_on:
            - denda_db
            - denda_cache
        environment:
            - REDIS_PORT=6379
            - REDIS_HOST=denda_cache
        networks:
            - iae_shared_network

    denda_db:
        image: mysql:8.2
        container_name: denda_db
        environment:
            - MYSQL_ROOT_PASSWORD=123
            - MYSQL_DATABASE=denda_service
        ports:
            - "33067:3306"
        volumes:
            - denda_data:/var/lib/mysql
        networks:
            - iae_shared_network

    denda_cache:
        image: redis:latest
        container_name: denda_cache
        ports:
            - "63797:6379"
        networks:
            - iae_shared_network

    denda_phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: denda_phpmyadmin
        depends_on:
            - denda_db
        environment:
            - PMA_HOST=denda_db
            - PMA_USER=root
            - PMA_PASSWORD=123
            - VIRTUAL_HOST=pma.denda.test
        networks:
            - iae_shared_network

volumes:
    denda_data: